name: Development workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run StyleLint
        run: npm run lint:styles

      - name: Build Docker container
        run: docker build -t voronadya/task-manager:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Log in to Docker Hub
        run: docker login -u voronadya -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker container to Docker Hub
        run: docker push voronadya/task-manager:latest
